<#
.SYNOPSIS
    Compatibility entry point for the 1.5.1 two-binary recovery.

.DESCRIPTION
    Run from a folder containing Recover-Givova.ps1 and the two official binaries.
    The USB package generated by Build-GivovaMonitor.ps1 is the supported delivery.
#>
[CmdletBinding(PositionalBinding = $false)]
param(
    [string]$SourceAgentExe = "",
    [string]$SourceUpdaterExe = "",
    [string]$InstallDir = "C:\ProgramData\GivovaMonitor"
)

$ErrorActionPreference = "Stop"
# Windows PowerShell 5.1 leaves $PSScriptRoot empty inside param() defaults under -File.
$packageDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
if (-not $SourceAgentExe) { $SourceAgentExe = Join-Path $packageDir "GivovaMonitorAgent.exe" }
if (-not $SourceUpdaterExe) { $SourceUpdaterExe = Join-Path $packageDir "GivovaMonitorUpdater.exe" }

$recoveryScript = Join-Path $packageDir "Recover-Givova.ps1"
if (-not (Test-Path -LiteralPath $recoveryScript -PathType Leaf)) {
    throw "Recover-Givova.ps1 nao foi encontrado ao lado deste script. Use o pacote GivovaRecovery-1.5.1 gerado pelo build oficial."
}

& $recoveryScript -SourceAgentExe $SourceAgentExe -SourceUpdaterExe $SourceUpdaterExe -InstallDir $InstallDir
exit $LASTEXITCODE
